#ifndef _UI_H
#define _UI_H

#define INPT_CMD_MAX_LENGTH 20 // QUANTIDADE MAXIMA DE CARACTERES PARA INSERIR NO INPUT
#define INPT_MAX_LENGTH 100 // QUANTIDADE MAXIMA DE CARACTERES PARA INSERIR NO INPUT
#define SET_MAX_LENGTH INPT_MAX_LENGTH

void ui_run();

#endif